Use MSVC toolchain on windows instead of mingw
- minor fixes to enable MSVC compilation
  - check for feature support as well as existence of header with guarded includes
  - use msvc branch of pdelab, multidomaingrid
  - chunk string literal to avoid string too long msvc error
  - workaround for msvc parser error C2947: expecting '>' to terminate template-argument-list, found '<'
- add a powershell build script for windows CI
- add an arm windows CI job